---
# DS Backup Playbook: Save current state before upgrade
#
# Usage:
#   ansible-playbook ds-backup-7.5.yml

- name: DS Backup
  hosts: "{{ inventory_host_vars }}"
  serial: 1
  gather_facts: true
  become: true
  become_user: forgerock

  tasks:
    - name: DS Backup
      include_role:
        name: IAM_ROLES
        tasks_from: ROLE_DS_BACKUP
