---
# DS Restore Playbook: Restore to pre-upgrade state
#
# Usage:
#   ansible-playbook ds-restore-7.5.yml

- name: DS Restore
  hosts: "{{ inventory_host_vars }}"
  serial: 1
  gather_facts: true
  become: true
  become_user: forgerock

  tasks:
    - name: DS Restore
      include_role:
        name: IAM_ROLES
        tasks_from: ROLE_DS_RESTORE
